### ISSUE TITLE
Syntax error after installation

### ISSUE THREAD

**Issue by gonetil** [fpiraneo/oclife#20]
I've installed oclife in a clean Owncloud (ver 8.0.4). After installation, the tag tree is not showing (I think there should be a root tag at least, should it?). And it won't let me do anything.

I am getting the following error instead:
<span class="fancytree-title" title="200: SyntaxError: Unexpected token <">Load error! (SyntaxError: Unexpected token &lt;) </span>

![seleccion_112](https://cloud.githubusercontent.com/assets/1521405/6314569/74a80e18-b9c2-11e4-8a46-ed8bd44f3f5f.png)

I know there might be an issue with OC 8 version, but I am not sure it actually that's the problem. 
What should be there in oclife tables? which rows should be in oc_appconfig table?

I am using php 5.4.36, apache2 and mysql 5.5 , just in case.

Thanks in advance

**Comment by TheDuke87** [comment]
Got the same issue, just upgraded to OC 8.0.2 and stumbled upon this addon.

**Comment by fpiraneo** [comment]
Gentleman, as written on the documentation, this addon is not compatible with OC8.
I'm sorry for that.

**Comment by TheDuke87** [comment]
Any chance to make it compatible?

**Comment by fpiraneo** [comment]
Hi Duke, as you can argue by my answer delay, actually it's hard to me to make a compatibility plan of this app; moreover from OC7 to OC8 the app handling has changed a lot so this compels me to study how this changed and estimate the efforts to make the changes on the app.

**Comment by TheDuke87** [comment]
Oh alright. I wasn't aware of the changes in app handling, it just looked like a random bug.
Please let me know when you need some testing done, I would be glad to help.

**Comment by fpiraneo** [comment]
Thank you for your offer. I plan to use OC8 in the future so I'll setup an OC8 testing environment.
