### ISSUE TITLE
made translation into german

### ISSUE THREAD

**Issue by go4oc** [fpiraneo/oclife#21]
hello francesco

i adapded and modifyd the german translation file de.php of the 'latest' oclife version (downloaded at 30.03.2015 from apps.owncloud.

how can i give it to you? i would prefere a simple method, because i haven't any knowledge of git hub.

by the way: in my opinon oclife is the most useful app of all owncloud apps.

kind regards, roland

**Comment by fpiraneo** [comment]
Hi Roland!
Thank you very much for your apreciation on my job.
For sure you can send the translation at fpiraneo@gmail.com and I'll integrate it on the source tree.
For sure I'll improve again oclife also if my spare time will get shorter, so stay tuned!
