### ISSUE TITLE
Open location of tagged image

### ISSUE THREAD

**Issue by HBMBR** [fpiraneo/oclife#25]
Hi

Is it possible to add an option to open an Image that you view after selecting a tag and then open to the location where it is - or open the folder - or Download it

**Comment by fpiraneo** [comment]
Hi, this feature is not implemented yet. The develop of oclife is frozen and is very unsuitable that other features will be implemented in future. OwnCloud API has been revealed too much mutable and not so much documented to rely on. I'm sorry for that but I don't have time to run against the moods of OwnClouds developers.
