### ISSUE TITLE
Owncloud 9.0

### ISSUE THREAD

**Issue by urba83** [fpiraneo/oclife#28]
Hi, I installed oclife in owncloud 9.0 under a ubuntu 15.10 Virtual Box VM; The app is enabled and the app is available from the menù, also the tag hierarchy graph is working. But under the file view, once I press the informations button, no popup is shown. Could you update compatibility also with owncloud 9.0? Thank you.

**Comment by fpiraneo** [comment]
Hi, at the time I have no really time to make any change / adaptation to ocLife, I'm very sorry for that. Maybe I'll revise that in the future but there is no planning.
Regards, Francesco
